manifest:
    remotes:
        -name: christoph
        url-base: https://github.com/thurnheer
    projects:
        - name: zephyr
          remote: christoph
          revision: v2.4.0
          west-commands: scripts/west-commands.yml
        - name: cop
          remote: christoph
          path: cop
    self:
        path:

